### ISSUE TITLE
Setting unknown property: born05\imagehotspots\models\Hotspot::canvasId

### ISSUE THREAD

**Issue by tomkiss** [born05/craft-imagehotspots#12]
Getting this error when attempting to load an edit entry page after a fresh install, Craft 4, with ImageHotpots set to a single field within the entry.

`Setting unknown property: born05\imagehotspots\models\Hotspot::canvasId`

**Comment by roelvanhintum** [comment]
Sorry for the late response. The `canvasId` part is not something of the ImageHotpots plugin. Maybe a conflicting plugin? It doesn't sound familiar. Was the field existing before changing it to the "Image Hotspot" field type? Sounds like old data from something else is loaded into the model.

**Comment by tomkiss** [comment]
Thanks for getting back to me on this.

I've reinstalled and tried again, but can't repro so this definitely seems like my mistake here. Apologies!
