### ISSUE TITLE
CraftCMS v. 5 support

### ISSUE THREAD

**Issue by JaneConvergine** [born05/craft-imagehotspots#16]
Are you going to support CraftCMS v.5? Do you have any timelines?

**Comment by roelvanhintum** [comment]
@JaneConvergine, thanks for pointing this out. Yes, we are planning on supporting Craft 5.

**Comment by JaneConvergine** [comment]
> @JaneConvergine, thanks for pointing this out. Yes, we are planning on supporting Craft 5.

We are thrilled to hear that! 

When will the updated version be available?

**Comment by roelvanhintum** [comment]
@JaneConvergine looks like Matrix fields (which are used a lot in combination with this field) work different than before, so it's going to take some time to refactor. I'm planning to get this released somewhere in the coming weeks.

**Comment by roelvanhintum** [comment]
@JaneConvergine, i've just added craft 5 support in 3.0.0-beta.1
It currently doesn't show all hotpots until nested entries have been opened once. So this needs some work, but it is functional.

**Comment by JaneConvergine** [comment]
> @JaneConvergine, i've just added craft 5 support in 3.0.0-beta.1 It currently doesn't show all hotpots until nested entries have been opened once. So this needs some work, but it is functional.

Wonderful! Thanks a lot for your support!!!!

**Comment by roelvanhintum** [comment]
Support isn't 100% complete. I'll keep this open until stable.

**Comment by roelvanhintum** [comment]
Stable isn't the right word. Anyway, matrix and supertable blocks currently won't show until that block has been opened once because of the new UI in Craft 5.

**Comment by svondervoort** [comment]
Any update on this?

We wan't to upgrade our sites to Craft 5, but it depends on if the used plugins have a full release instead of a beta release if we upgrade or not.

**Comment by roelvanhintum** [comment]
We've looked into this again and decided to release 3.0.0
The only thing i hoped to change, seems to conflict with how Craft 5 is intended. Everything now works just like before, except for hotspots which are nested in matrix or neo blocks, those are shown in the view after the edit modal of that block has opened once. Craft 5 won't load all that data immediately like in Craft 4, to make things faster.

**Comment by svondervoort** [comment]
@roel, there seems to be one issue in the release https://github.com/born05/craft-imagehotspots/issues/19. Or at least we are experiencing this issue with the picker.

**Comment by svondervoort** [comment]
@roelvanhintum there seems to be one issue in the release https://github.com/born05/craft-imagehotspots/issues/19. Or at least we are experiencing this issue with the picker.
