### ISSUE TITLE
Zoom-in/out feature for high-resolution images

### ISSUE THREAD

**Issue by JaneConvergine** [born05/craft-imagehotspots#17]
Hi @roelvanhintum ,

Could we consider integrating a zoom-in/out feature into your plugin? We're looking to upload high-resolution images (around 3000x5000 px), specifically detailed maps with approximately 300 rooms. The current upload size renders the maps too small to effectively tag specific locations. Could you let us know if this enhancement is feasible?

Thanks for your help!

**Comment by roelvanhintum** [comment]
@JaneConvergine, thank you! That would be a good feature! I'll get back to you on this.

**Comment by roelvanhintum** [comment]
This is released in 3.0.0-beta.2
Please let me know if this is working as expected.

**Comment by JaneConvergine** [comment]
> This is released in 3.0.0-beta.2 Please let me know if this is working as expected.

This works excellently! Thanks a lot for your prompt response and update!
