### ISSUE TITLE
[ Craft 5 ] [ Bug ] Weird offset when draging the hotspot or zooming in

### ISSUE THREAD

**Issue by svondervoort** [born05/craft-imagehotspots#19]
In the previous version (`2.0.0`) we have running on a Craft 4 site you could just click the location, now you have to drag and drop the hotspot.

In the Craft 5 version (`3.0.0-beta.3`) you have to drag the hotspots but there is a weird offset.

For this reason I think to coordinates of the hotspots are not correct:
![image](https://github.com/user-attachments/assets/8c95baea-0bbb-4060-bf3d-04b68ea35410)

I've recorded a video of what happens when trying to set the hotspot on an image or zooming: https://github.com/user-attachments/assets/4076f37c-4cd8-4443-a02f-a1f7c9b07445

**Comment by roelvanhintum** [comment]
Thanks @svondervoort! Fixed in 3.0.1

**Comment by svondervoort** [comment]
Thanks @roelvanhintum works perfectly now!
