### ISSUE TITLE
Multiple assets per entry

### ISSUE THREAD

**Issue by wallacio** [born05/craft-imagehotspots#2]
I have discovered that this doesn't allow multiple assets per entry. Or at least, the hotspot picker defaults to use the first asset in the list. 

It would be great to see this plugin able to handle multiple assets, and hotspots unique to those assets, all in the same entry.

**Comment by wallacio** [comment]
Update! This plugin is smarter than me. For anyone else finding themselves in this position, this appears to work:
- Create a Matrix field for your entry type
- Create a block, call it something like 'image with hotspots'
- Create two fields in this block: 
  - One for the asset (remember the block name)
  - A Supertable to contain the hotspots, call it something like 'markers'. Create Supertable fields:
    - label (Text)
    - marker (Image Hotspot), enter the name of the block containing the asset above
    - links to (Entry) - or whatever you'd like to link to

Now, using multiple images with hotspots is a case of adding matrix blocks until your browser can't cope.

**Comment by roelvanhintum** [comment]
@wallacio thanks for the update! I tried to describe this, if the docs are unclear please let me know. It uses tree traversal to find the first field with a matching name. So there could be multiple levels between the fields. You could also use the same pattern and names at a different depths in your tree as long as they don't cross.

Are you still missing functionality or does this solve it for you?

**Comment by wallacio** [comment]
No missing functionality but if there's any improvement to the docs to be made it would be an example of how to include multiple images, themselves with multiple hotspots in an entry. My use-case is various perspectives/views of a map (as an image, nothing with lat/long) on a page, map having a different placement of markers. 

Thanks!

**Comment by matteveryday** [comment]
Hi @roelvanhintum I'm curious if the Image hotspot field supports the Neo plugin for building complex matrixes? I'm trying to set this up inside of a Neo block and not seeing the Hotspot button. My first guess is that there's an issue with the hierarchy / placement of the fields within the tree, but not sure if I'm missing something?

<img width="885" alt="Screen Shot 2021-04-30 at 9 00 50 AM" src="https://user-images.githubusercontent.com/29387497/116698697-a85e3e00-a992-11eb-9c95-4c1af31d8c49.png">

**Comment by roelvanhintum** [comment]
@matteveryday, the plugin traverses the tree, so it should find the field. I don't know if this works different with Neo.

Judging by the screenshot, the entry should be saved first after adding an image. The button should be visible after saving.

**Comment by matteveryday** [comment]
I should have mentioned that the screenshot is after already saving the entry. ha.

**Comment by roelvanhintum** [comment]
@matteveryday how is your field structured? I'm having some trouble reproducing this.

**Comment by roelvanhintum** [comment]
@matteveryday fixed in 1.1.0

**Comment by matteveryday** [comment]
@roelvanhintum Thank you!  I updated and everything is working nicely now 😄
