### ISSUE TITLE
FR: Zoom/pan on high resolution images to place markers

### ISSUE THREAD

**Issue by wallacio** [born05/craft-imagehotspots#3]
I had a look at doing this myself as a PR but soon discovered I'd opened a can of worms. Finding the absolute X/Y coordinates on an image which is zoomed/panned is 'just' maths, but nothing I'm going to get to at the moment.

I think it'd be a great addition though. Again, a slightly uncommon but appropriate use-case is a spherically rendered image, which is made navigable on the front end using Three.js. In resolution terms, it's fairly big and placing markers on the flat version in CP is a bit hit-and-miss. Allowing zoom and pan to place markers would make this much more accurate.

**Comment by roelvanhintum** [comment]
Thanks @wallacio, this looks like a good feature to have!

**Comment by roelvanhintum** [comment]
Took a while, but is handled in 3.0.0-beta.2
