### ISSUE TITLE
FR: Support linking hotspots as a custom field within an Asset Volume

### ISSUE THREAD

**Issue by matteveryday** [born05/craft-imagehotspots#7]
I'm curious if it's possible to add one or multiple (via matrix) hotspots to an image via a custom field within that image's asset volume. The goal would be that wherever that particular image were used, the hotspot data would be maintained and available in the templates. 

<img width="1565" alt="Screen Shot 2021-07-02 at 4 29 20 PM" src="https://user-images.githubusercontent.com/29387497/124326159-fee32680-db53-11eb-8530-29e3977054cb.png">

Conceptually, when I query for an asset, I can access all of it's hotspots directly...

```twig
{% set image = entry.assetFieldHandle.one() %}
<div style="position: relative">
    <img src="{{ image.url() }}" style="width: 100%;" />
    {% for tag in image.productTags %}
        {% if tag.hotspotTag|length %}
        <div style="position: absolute; top: {{ tag.hotspotTag.y * 100 }}%; left: {{ tag.hotspotTag.x * 100 }}%"></div>
        {% endif %}
    {% endfor %}
</div>
```

Hoping my explanation makes sense, but happy to clarify any questions if need be.

**Comment by roelvanhintum** [comment]
Hi @matteveryday, currently this doesn't work, but adding it directly to an asset seems like a good addition!

**Comment by roelvanhintum** [comment]
@matteveryday 1.2.0 has support for your setup.
